name: 🚀 Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    paths-ignore:
      - package*.json
      - docs/changelog.md
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: generate changelog
        uses: orhun/git-cliff-action@v4.4.2
        id: git-cliff
        with:
          config: ./docs/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: tmp/changelog.md
          GITHUB_REPO: ${{ github.repository }}
      - name: bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
      - name: configure git
        run: |
          git config --global user.name "mateothegreat[bot]"
          git config --global user.email "mateothegreat[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
      - name: npm version
        run: npm version ${{ steps.tag.outputs.new_tag }} --force
      - name: concat changelogs
        run: |
          cat ${{ steps.git-cliff.outputs.changelog }} > tmp/new_changelog.md
          cat docs/changelog.md >> tmp/new_changelog.md
          mv tmp/new_changelog.md docs/changelog.md
      - name: commit
        run: |
          git add docs/changelog.md package.json
          git commit -am "chore(release): update changelog and bumping package.json"
          git push origin HEAD:main
      - name: write to .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: npm publish
      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
  notify:
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          status: ${{ needs.build.result }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
